service: dio-serverless-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: sa-east-1

functions:
  api:
    handler: index.handler
    events:
      - httpApi:
          path: /
          method: get
